#! /usr/bin/env bash

echo "Rebuilding the UI..."
cd "$(dirname "${BASH_SOURCE[0]}")/../src/ui"
npm run deploy

echo "Checking for changes..."
git diff --quiet --exit-code
if [ $? -eq 1 ]; then
  echo "Changes detected. Staging and appending to the last commit..."

  git add -A
  git commit --no-verify --quiet --message "chore: rebuild the project"

  exit 1
else
  echo "No changes detected."

  exit 0
fi
