# This workflow will do a clean installation of node dependencies, cache/restore them, and build the UI code.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build UI code

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "src/ui/**"
  pull_request:
    branches: ["main"]
    paths:
      - "src/ui/**"

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ui
    strategy:
      matrix:
        node-version: ["22.14.0"]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"
      - name: Install dependencies
        run: npm install
      - name: Install rollup
        run: npm install @rollup/rollup-linux-x64-gnu
      - name: Build
        run: npm run build
