name: Nightly Release

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
        default: true
        description: Put PR in draft mode for testing

jobs:
  nightly-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: version tag
        id: version-tag
        run: |
          tag="0.0.$(date +"%Y%m%d%H%M%S")"
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install wheel numpy twine
      - name: Build Package
        run: |
          cd ./src/builtin-adapter
          ./python/pip_package/build_pip_package.sh ${{ steps.version-tag.outputs.tag }}
      - name: Verify the Distribution
        run: twine check ./src/builtin-adapter/gen/adapter_pip/dist/*
      - name: Check Directory Output
        run: ls -l ./src/builtin-adapter/gen/adapter_pip/dist/*.whl
